= ryanabx-shell

A compositor-agnostic desktop shell!

NOTE: This project is under heavy development, and will probably not be "stable" for a while.

Welcome to a desktop shell that's intended to run on any compositor! To be more specific, this would be any compositor that implements `wlr-layer-shell`.

The currently planned compositors to be supported are:

* https://github.com/pop-os/cosmic-comp[cosmic-comp] (First primary target)
* https://invent.kde.org/plasma/kwin[KWin]
* https://gitlab.freedesktop.org/wlroots/wlroots[Wlroots-based compositors]

This shell is intended to be similar to Windows-style desktops, with a launcher in the bottom left, a list of favorite apps in the middle or left (configurable), and a tray with settings on the right! The designs aren't fully finished at the moment, but that's the general direction I'd like to go.

The shell is proudly built entirely in https://www.rust-lang.org/[Rust]! 

== Build instructions (Ubuntu/Fedora instructions)

[source, shell]
----
# Install Dependencies (Ubuntu)
sudo apt-get install -y libxkbcommon-dev
# Install Dependencies (Fedora)
sudo dnf install -y libxkbcommon-devel
# Build
cargo build
----

== Contributing

Since a lot of the development is personal, the first thing you should do if you'd like to contribute is https://github.com/ryanabx/ryanabx-shell/issues/new[submit an issue] describing the feature you'd like to implement. This helps to avoid potential duplicate work if I'm already working on such a feature!