name: deploy website

on:
  workflow_dispatch:
  push:
    branches:
      - master  # Run the action on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Cargo
      run: sudo apt-get install cargo

    - name: Install simple-ssg
      run: cargo install simple-ssg

    - name: Generate static site
      run: ~/.cargo/bin/simple-ssg -t github-markdown --clean ./docs -o ./output

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
